version: "3.9"

services:

  server-service:
    image: 'nginx:stable-alpine'
    # build:
    #   context: .
    #   dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8001:80'
    volumes: 
    #   - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  #ro-readonly
#     depends_on: 
#       - php
#       - mysql


  php-service: # the port settings is directly mentioned in the nginx/nginx.conf file
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes: 
      - ./source-code:/var/www/html:delegated #delegated for performance improvements, changes in file will not be reflected immediately, will take time to get updated


  mysql-service:
    image: mysql:8.0
    env_file: 
      - ./environment-settings/mysql.env


  composer-service:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./source-code:/var/www/html
#   artisan:
#     build:
#       context: .
#       dockerfile: dockerfiles/php.dockerfile
#     volumes: 
#       - ./src:/var/www/html
#     entrypoint: ["php", "/var/www/html/artisan"]
#   npm:
#     image: node:14
#     working_dir: /var/www/html
#     entrypoint: ["npm"]
#     volumes: 
#       - ./src:/var/www/html
