version: "3.9"

services:

  server-service:
    image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile #because we are using copy cmd in the custom nginx image, the context should be set in the root where docker-compose.yaml file is present
    ports: 
      - '8001:80'
  #comment the bind mount(volumes) if you are in production , then uncomment in development mode      
    volumes: 
      - ./source-code:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  #ro-readonly
    depends_on: 
      - php-service
      - mysql-service


  php-service: # the port settings is directly mentioned in the nginx/nginx.conf file
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
  #comment the bind mount(volumes) if you are in production , then uncomment in development mode
    volumes: 
      - ./source-code:/var/www/html:delegated #delegated for performance improvements, changes in file will not be reflected immediately, will take time to get updated


  mysql-service:
    image: mysql:8.0
    env_file: 
      - ./environment-settings/mysql.env


  composer-service:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./source-code:/var/www/html


  artisan-service:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./source-code:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]


  npm-service:
    image: node:14.17.4
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./source-code:/var/www/html
